server:
  port: 2000
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 753850385187-79rbsnokc67tcvbv9l7sh8dnic739ft4.apps.googleusercontent.com
            clientSecret: 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
Spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/market
    username: market
    password: 123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate:
      ddl-auto: update
jwt:
  token:
    secret: hellojwt
    validity: 8400000